version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:12.3-alpine

    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    container_name: fastAPI_Quiz
    command: uvicorn app.main:app --host 0.0.0.0
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/code/app
      - ./alembic:/code/alembic
      - ./alembic.ini:/code/alembic.ini
