version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:12.3-alpine

    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: unless-stopped