"""change name

Revision ID: cbd548017a0f
Revises: 529f097751f8
Create Date: 2023-10-11 18:56:53.255677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd548017a0f'
down_revision: Union[str, None] = '529f097751f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('answer', sa.String(), nullable=True))
    op.drop_index('ix_questions_question_text', table_name='questions')
    op.create_index(op.f('ix_questions_question'), 'questions', ['question'], unique=False)
    op.drop_column('questions', 'question_text')
    op.drop_column('questions', 'answer_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answer_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('question_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_questions_question'), table_name='questions')
    op.create_index('ix_questions_question_text', 'questions', ['question_text'], unique=False)
    op.drop_column('questions', 'answer')
    op.drop_column('questions', 'question')
    # ### end Alembic commands ###
